name: Build and test
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: ./.github/actions/setup
    - name: Test
      run: |
        go test -v ./pcb
        go test -v ./netlist
        go test -v ./swriter
        go test -v ./kcgen
        go test -v ./kcsl
        go test -v ./kite
    - name: Build binaries
      run: |
        set -xe
        go version
        go build -v -o output/kcgen kcgen/*.go
        go build -v -o output/kite kite/*.go
        cp -v kite/*.glade output/
        echo ========================================
        mkdir kcgen_pkg
        mkdir -pv kcgen_pkg/DEBIAN
        mkdir -pv kcgen_pkg/usr/bin
        cp .github/kcgen_control kcgen_pkg/DEBIAN/control
        cp output/kcgen kcgen_pkg/usr/bin
        dpkg-deb --build kcgen_pkg ./output
        echo ========================================
        mkdir kite_pkg
        mkdir -pv kite_pkg/DEBIAN
        mkdir -pv kite_pkg/usr/bin
        mkdir -pv kite_pkg/usr/share/kite
        cp .github/kite_control kite_pkg/DEBIAN/control
        cp output/kite kite_pkg/usr/bin
        cp output/*.glade kite_pkg/usr/share/kite
        dpkg-deb --build kite_pkg ./output
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts.zip
        path: |
          output/**
